import { ReactElement, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import CardCarousel from "components/CardCarousel";
import Layout from "components/Layout";
import type { NextPageWithLayout } from "./random2398";

const Home: NextPageWithLayout = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <CardCarousel cardContainerVariant="square" />
        <CardCarousel cardContainerVariant="tallboy" />
        <CardCarousel cardMediaHeight={140} />
      </main>
    </div>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};

export default Home;
