import { ReactElement, useEffect } from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.css";
import CardCarousel from "components/CardCarousel";
import Layout from "components/Layout";
import type { NextPageWithLayout } from "./random2398";
import { useVerifyTwitterCallbackTokensMutation } from "services/auth";

const Home: NextPageWithLayout = () => {
  const router = useRouter();
  const { oauth_token, oauth_verifier } = router.query;
  const [trigger, result] = useVerifyTwitterCallbackTokensMutation();

  console.log("log mutation result", result);

  useEffect(() => {
    if (oauth_token && oauth_verifier) {
      trigger({ oauth_token, oauth_verifier });
    }
  }, [oauth_token, oauth_verifier]);

  console.log("show router query", router.query);
  console.log("oauth_token", oauth_token);
  console.log("oauth_verifier", oauth_verifier);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <CardCarousel cardContainerVariant="square" />
        <CardCarousel cardContainerVariant="tallboy" />
        <CardCarousel />
      </main>
    </div>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};

export default Home;
